# PurityKits - A customisable kit plugin for Crystal PVP servers.
# Written by chiralpenguin for the Purity Network
# Based on "PlayerKits" by Ajneb97 - https://github.com/Ajneb97/PlayerKits
verbose: false