name: PurityKits
main: com.purityvanilla.puritykits.PurityKits
version: 1.1
api-version: 1.21
commands:
  kit:
    aliases: k
    permission: puritykits.kitcommand
  spawn:
    permission: puritykits.spawn
  reload:
    permission: puritykits.reload